# Generated by Django 3.0.5 on 2023-04-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20230408_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
