# Generated by Django 3.0.5 on 2023-04-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20230409_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='min',
            new_name='minu',
        ),
    ]
