# Generated by Django 3.2.5 on 2023-04-16 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_active'),
        ('exam', '0011_result_exam_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='exam_pic',
        ),
        migrations.CreateModel(
            name='Exam_pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_pic', models.ImageField(blank=True, null=True, upload_to='exam_pic')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
