# Generated by Django 3.2.5 on 2023-04-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20230416_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pass_marks',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
