# Generated by Django 3.0.5 on 2023-04-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.AddField(
            model_name='teacher',
            name='exam_password',
            field=models.CharField(default='12345678', max_length=10),
        ),
    ]
