# Generated by Django 3.0.5 on 2023-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20230408_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='active',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
