# Generated by Django 3.0.5 on 2023-04-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
